version: "3.9"

services:

  xray:
    image: teddysun/xray:latest
    container_name: xray-exit
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./xray/config.json:/etc/xray/config.json

  wireguard:
    image: linuxserver/wireguard
    container_name: wg-exit
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
    volumes:
      - ./wireguard:/config
    restart: unless-stopped